### ISSUE TITLE
You made a game quickly enough for a jam in Rust

### ISSUE THREAD

**Issue by snoopdouglas** [robsws/yo-ho-ho-and-an-alien-gun#1]
How

**Comment by robsws** [comment]
🤣Not going to lie, it was difficult. Especially given the game engine is still very young. Rust is great though, it's spoiled all other languages for me

**Comment by snoopdouglas** [comment]
Lol, that is pretty great. That's the position I'm in too - though am also waiting for Godot 4 to come out so Rust with that will be bearable...
